---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: basic-auth
  namespace: aks-istio-system
spec:
  selector:
    matchLabels:
      istio.io/gateway-name: cheshire-cat
  url: oci://ghcr.io/istio-ecosystem/wasm-extensions/basic_auth:1.12.0
  phase: AUTHN
  pluginConfig:
    basic_auth_rules:
      - prefix: "/admin"
        request_methods:
          - "GET"
          - "POST"
          - "HEAD"
          - "PUT"
        credentials:
          - "admin:admin"
